db.zips.find({"state":"MO"},{"city": 1, "state": 1})
db.zips.find({$or:[{"state" : "MO"}, {"state": "FL"}, {"state": "IA"}, {"state": "KS"}]}, {"city": 1, "_id": 1})
db.zips.find({"state":"OH", "pop": {$lt: 2000}}, {"city": 1, "pop": 1})
db.zips.find({"pop": {$gt: 50000}}, {"city": 1, "pop": 1})
db.zips.find({"city": "COLUMBIA", "state": "MO"}, {"_ID": 1})
db.zips.aggregate([{$match: {"state": "MO"}}, {$group: {_id: "$_id", totalPop: {$sum: "$pop"}}}])
db.zips.find({"city": "SPRINGFIELD"}, {"state": 1, "city": 1, "_id": 0})
db.zips.find({"city": "SPRINGFIELD"}).count()
db.zips.find({"city": "EMERALD"}, {"_id": 1, "pop": 1, "state": 1})
db.zips.find({"pop": 10}, {"_id": 1, "city": 1, "state": 1})
db.stocks.find()
db.stocks.find({"Sector": "Information Technology"}, {"Name": 1, "Symbol": 1, "_id": 0})
db.stocks.find({"Sector": "Financials", "Price": {$gt: 75}}, {"Name": 1, "Symbol": 1, "Price": 1, "_id": 0})
db.stocks.find({"EBITDA": {$gt: 2500000000}}, {"Name": 1, "Sector": 1, "EBITDA": 1, "_id": 0})
db.stocks.find({"52 Week High": {$gte: 150}}, {"Name": 1, "Symbol": 1, "Sector": 1, "_id": 0})
db.stocks.find({"Sector": "Real Estate", "Price": {$lt: 50}}, {"Name": 1, "Symbol": 1, "Price": 1, "_id": 0})
db.stocks.find({$or:[{"Sector": "Utilities"}, {"Sector": "Industrials"}]}, {"Name": 1, "Dividend Yield": 1,"Symbol": 1, "_id": 0})
db.stocks.find({$or:[{"Dividend Yield": {$gt: 3}}, {"Earnings/Share": {$lt: 1}}]}, {"Name": 1, "Symbol": 1, "Market Cap": 1, "_id": 0})