DESCRIBE customer;
DESCRIBE agents;
SELECT CUST_NAME,GRADE FROM customer;
SELECT AGENT_CODE,AGENT_NAME, WORKING_AREA FROM agents;
SELECT ORD_NUM,ORD_AMOUNT,ORD_DATE FROM orders;
SELECT CUST_CODE,CUST_NAME,CUST_COUNTRY,PHONE_NO FROM customer WHERE CUST_COUNTRY = "USA";
SELECT AGENT_NAME,PHONE_NO FROM agents WHERE WORKING_AREA = "Bangalore"; -- "Country" was blank
SELECT * FROM orders WHERE ADVANCE_AMOUNT = 100;
SELECT CUST_NAME FROM customer WHERE GRADE = 2;
SELECT * FROM customer WHERE CUST_CITY = "New York";
SELECT * FROM agents WHERE  WORKING_AREA = "London" AND COMMISSION > 0.12;
SELECT ORD_NUM,AGENT_CODE,CUST_CODE FROM orders WHERE ADVANCE_AMOUNT <= 500 AND ORD_AMOUNT >= 1500;
SELECT CUST_CODE,CUST_NAME,AGENT_CODE,OUTSTANDING_AMT FROM customer WHERE OUTSTANDING_AMT > 6000 AND PAYMENT_AMT <= 3000;
SELECT ORD_NUM FROM orders WHERE ORD_AMOUNT < 1000;
SELECT CUST_NAME FROM customer WHERE CUST_COUNTRY = "India" AND OUTSTANDING_AMT < 10000;